### ISSUE TITLE
No perp account for basket token USDC

### ISSUE THREAD

**Issue by viralhysteria** [blockworks-foundation/mango-explorer#11]
Using the MarketMakingQuickstart readme step-by-step (using WSL2 properly configured), returns following error after calling account balance in second step of part 9

> Traceback (most recent call last):
>   File "/app/bin/show-account-balances", line 78, in <module>
>     report: mango.AccountInstrumentValues = mango.AccountInstrumentValues.from_account_basket_base_token(
>   File "/app/mango/accountinstrumentvalues.py", line 114, in from_account_basket_base_token
>     raise Exception(f"No perp account for basket token {account_slot.base_instrument.symbol}")
> Exception: No perp account for basket token USDC

usdc deposit was however subtracted from account without error

also, there seems to be an issue with displaying some characters on WSL but i'm not sure if that's on WSL side, i've tried cycling a couple different mono fonts

![ubuntu2004_bJgxBoMgJQ](https://user-images.githubusercontent.com/1983431/141594047-a384ecff-1763-4fc8-a50c-6dfc6ab4a550.png)

**Comment by OpinionatedGeek** [comment]
Hi,

Apologies - this should be fixed now in v3.2.3 if you pull the latest code.

As for WSL, it looks like either that subsystem or that terminal just isn't displaying Unicode properly - you should see object types like 𝙸𝚗𝚜𝚝𝚛𝚞𝚖𝚎𝚗𝚝𝚅𝚊𝚕𝚞𝚎 and 𝙿𝚛𝚒𝚌𝚎𝚍𝙰𝚌𝚌𝚘𝚞𝚗𝚝𝙸𝚗𝚜𝚝𝚛𝚞𝚖𝚎𝚗𝚝𝚅𝚊𝚕𝚞𝚎𝚜.

**Comment by viralhysteria** [comment]
Thanks, the new pull did in fact fix the issue No problems, finishing the rest of the quick start. 

Unicode display seems to be a long standing issue on WSL/Terminal based on their github due to poor (or no handling) for fallback fonts. 
https://github.com/microsoft/Terminal/issues/306
https://github.com/microsoft/terminal/issues/190

Running WSL through windows terminal after the update in the following issue fixed my output
https://github.com/microsoft/terminal/pull/10478#issuecomment-878540381

![WindowsTerminal_32SHYbJCN1](https://user-images.githubusercontent.com/1983431/141645950-e862798f-854e-44e3-82dc-5f99c951b57f.png)

**Comment by OpinionatedGeek** [comment]
Excellent - glad it's working for you now, and apologies for the problems.

Thanks also for the info on the WSL problems - interesting stuff!
