### ISSUE TITLE
need to use Genesys Go RPC servers

### ISSUE THREAD

**Issue by 5QgKxT2j** [blockworks-foundation/mango-explorer#15]
I often encountered "NodeIsBehindException" using default mainnet RPC servers.
I heard that Genesys Go's RPC servers are stable and it can be used on Web UI.
Would you instruct how to use it on mango-explorer market making bot?
It seems it will work well by adding solana program information to ids.json.

**Comment by OpinionatedGeek** [comment]
`NodeIsBehindException` is unfortunately a common problem these days. Some RPC servers can't seem to keep up when under load.

As described in the 'Common Command Parameters' section of the Quickstart you can use any RPC server just by specifying its URL in the `--cluster-url` parameter, e.g.
```
mango-explorer marketmaker --cluster-url https://your-url.genesysgo.net/ ...
```
Alternatively you can specify it by an environment variable if you prefer.

I don't think it's the place of the ids.json file to hold other people's private RPC node URLs though - the ids.json file is for general Mango configuration, not for end-user configurations. End-user configuration for `mango-explorer` aims to be via command-line parameters.
