### ISSUE TITLE
How to get current orderbooks in Mango Markets without both own wallet and account?

### ISSUE THREAD

**Issue by outk** [blockworks-foundation/mango-explorer#32]
Hi all.
I'm a Python programmer and a cryptocurrency trader.
I would like to get current orderbooks of any symbol in Mango Markets for trading.
If you can, please give me some example.
Thank you, your countribution.

**Comment by OpinionatedGeek** [comment]
There's a repo of examples for `mango-explorer` that really is worth checking out:
    https://github.com/blockworks-foundation/mango-explorer-examples

In particular, there's an example for showing an orderbook:
    https://github.com/blockworks-foundation/mango-explorer-examples/blob/main/ShowOrderBook.ipynb

And since it's a Jupyter notebook, you can run the code in your browser without having to install any dependencies:
    https://mybinder.org/v2/gh/blockworks-foundation/mango-explorer-examples/HEAD?labpath=ShowOrderBook.ipynb

**Comment by outk** [comment]
Thank you for your kind.
I could run these examples at local, but I still don't know how to get real-time orderbooks on 'mainnet'.
Must I create my account to get real-time orderbooks on 'mainnet'?

**Comment by OpinionatedGeek** [comment]
You should be able to just change `cluster_name="devnet"` to `cluster_name="mainnet"` to run that example on mainner.

**Comment by outk** [comment]
I tried with [this example](https://github.com/blockworks-foundation/mango-explorer-examples/blob/main/ShowOrderBook.ipynb), but it doesn't work.
When `cluster_name="devnet"`, result is 
```
« OrderBook SOL-PERP [spread: 1.11000000, 0.804%]
        BUY       5,172.43000000 at         138.04000000   :: SELL       2,586.21000000 at         139.15000000
        BUY      10,344.86000000 at         137.83000000   :: SELL       5,172.43000000 at         140.83000000
        BUY       2,586.21000000 at         137.77000000   :: SELL      10,344.86000000 at         142.02000000
        BUY       1,378.00000000 at         135.62000000   :: SELL           1.00000000 at         143.20000000
        BUY     677,548.77000000 at         135.36000000   :: SELL       8,261.13000000 at         312.52000000
»
Example complete.
```
But when `cluster_name="mainnet"`, result is 
```
Traceback (most recent call last):
  File "{file_location}", line 13, in <module>
    account = accounts[0]
IndexError: list index out of range
```

**Comment by OpinionatedGeek** [comment]
Yeah, sorry. That won't work. I was about to tell you but you got your message in first. Apologies

You don't need an account on mainnet just to read data like the orderbook.

You do, however, need an account to run that particular example. Sorry.

This example may be more fitting for you:
    https://github.com/blockworks-foundation/mango-explorer-examples/blob/main/ShowStreamingOrderBook.ipynb

You don't need an account for it, you can change devnet to mainnet and it should work, and this example uses a websocket to stream live updates of the orderbook.

**Comment by outk** [comment]
Finally I could get real-time orderbooks!!
Thank you a lot of your kind.

I am also waiting for implementing a function to get them with REST API without creating my wallet account.

**Comment by OpinionatedGeek** [comment]
You're very welcome.

If you're looking for a REST API (or thinking of implementing one) this might be useful to you:
    https://github.com/blockworks-foundation/mango-v3-service
