### ISSUE TITLE
Issues on using pip to install package list on pypi

### ISSUE THREAD

**Issue by JimCurryWang** [blockworks-foundation/mango-explorer#49]
As the title described, before raising this ticket I also try to ``pip install --upgrade pip``, but it still did not work for me.

``pip install mango-explorer``
``pip install mango-explorer==3.4.6``
ERROR: Could not find a version that satisfies the requirement mango-explorer==3.4.6 (from versions: none)

**Comment by OpinionatedGeek** [comment]
Interesting... What you're doing should work.

Can you please let me know the version numbers of `python` and `pip` that you're using? (`mango-explorer` requires Python 3.9 or higher.)

**Comment by JimCurryWang** [comment]
@OpinionatedGeek 

> mango-explorer requires Python 3.9 or higher.)

I guess it might be the problem, as I am using python 3.8. Thanks for the clarification.
