### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by csc5a2g** [blockworks-foundation/mango-explorer#62]
Hi,

Anyone else noticed that they are now getting ? When I use the show account data example with my own key I get "List Index out of range" error  ?

Is this related to the addition of the "GMT-PERP" ?

Thanks
A.

**Comment by csc5a2g** [comment]
Scrub this just seen that @riordanp has corrected this error. 

A.

**Comment by riordanp** [comment]
@csc5a2g a new version of the package is now available with the fix for this and the new GMT market ids
