### ISSUE TITLE
Account.from_layout IndexError bug

### ISSUE THREAD

**Issue by fl4p** [blockworks-foundation/mango-explorer#63]
I get an IndexError in line [400](https://github.com/blockworks-foundation/mango-explorer/blob/main/mango/account.py#L400).

Changing line 358 to `[] for _ in range(len(group.slot_indices))` fixes it, not sure about any side effects.

**Comment by riordanp** [comment]
hey @fl4p please pull the latest code on `main` or upgrade your package, this was fixed in 3.4.8
