### ISSUE TITLE
This lib is taking  screenshots ?!

### ISSUE THREAD

**Issue by 2Spartiate** [blockworks-foundation/mango-explorer#64]
Once installed, and run :

- I got security warnings over Ghostscript dev right
- Once i bypassed this warnings in my own conf, and run an example script, i found... A screenshot of my shell appeared in the working directory !

I've installed it with pip3, with your source.
What's going on ?

**Comment by 2Spartiate** [comment]
The examples ones from the official website :

https://docs.mango.markets/developer-resources/code-examples

When starting one of the script with python2, a file name "Mango" would appear in the directory (and a "xwindow-like" cursor. Clicking on the file show a FHD screenshots of my current shell...

**Comment by kinghchan** [comment]
"_When starting one of the script with python2_" -- which script exactly did you run?

**Comment by 2Spartiate** [comment]
- Subscribe to an Order Book
- Get an Order Book snapshot
- Post Orders

**Comment by kinghchan** [comment]
the source code in this repo doesn't show anything dodgy. any chance you could send over a screenshot of the code you're seeing that's taking the screenshot?

**Comment by 2Spartiate** [comment]
I've got nothing on the shell. It freeze for a few seconds, then a cross-shaped pointer appears, then if i stricke a key, the cursor on the shell move fast (empty / unicode characters), then the app dies.

If the pb is not from the example codes, then it must be :
- either from your lib 
- or one of its dependencies 
(FYI this never happened prior to this installation)

That's a lot to checkout. I'd need a grep command searching for a Ghostscript / imagemagick command into python2/python3 libs...

**Comment by 2Spartiate** [comment]
After reinstalling linux pb is gone...
Closing this ticket now (opening another one)
